# 1. Dónde está el código REAL de tu aplicación 
# (Si usas la carpeta src, pon src. Si tienes los componentes fuera, añádelos separados por coma)
sonar.sources=src

# 2. Qué quieres IGNORAR por completo (Archivos de config, carpetas de build, dependencias)
# Los asteriscos ** significan "en cualquier carpeta"
sonar.exclusions=node_modules/**, .next/**, out/**, public/**, *.config.*, *.setup.*, .github/**

# 3. Dónde están tus tests
# Sonar aplicará reglas mucho más relajadas a esta carpeta (permitirá código duplicado, por ejemplo)
sonar.tests=e2e, tests
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts